#include <cstdint>
#include "Logger.h"
#include "KIntranetAuthSdk.h"
#include "KIntranetAuthorize.h"

static const QString _allFeatures[] = {
    QLatin1String("excel_split_merge", 17),
    QLatin1String("screen_recording", 16),
    QLatin1String("split_merge_tool", 16),
    QLatin1String("pdf_split", 9),
    QLatin1String("pdf_merge", 9),
    QLatin1String("doc_lose_weight", 15),
    QLatin1String("img_loss_compress", 17),
    QLatin1String("ocr", 3),
    QLatin1String("et_filter", 9),
    QLatin1String("data_comparison", 15),
    QLatin1String("gbbasicfunction", 15),
    QLatin1String("gbofficialfunction", 18),
    QLatin1String("gbofficialprintfunction", 23),
    QLatin1String("gjbbasicfunction", 16),
    QLatin1String("gjbofficialfunction", 19),
    QLatin1String("pdf2doc", 7),
    QLatin1String("pdf_2doc", 8),
    QLatin1String("pdf_2doc_local", 14),
    QLatin1String("pdf_2et_local", 13),
    QLatin1String("pdf_2ppt_local", 14),
    QLatin1String("pdf_split_local", 15),
    QLatin1String("pdf_merge_local", 15),
    QLatin1String("pdf_2cad_local", 14),
    QLatin1String("pdf_2cad", 8),
    QLatin1String("cad_2pdf_local", 14),
    QLatin1String("cad_2pdf", 8),
    QLatin1String("pdf_2txt_local", 14),
    QLatin1String("pdf_2txt", 8),
    QLatin1String("pdf_2img_pdf_local", 18),
    QLatin1String("pdf_2img_pdf", 12),
    QLatin1String("pdf_caj2pdf_local", 17),
    QLatin1String("pdf_caj2pdf", 11),
    QLatin1String("pic_2pdf_local", 14),
    QLatin1String("pic_2pdf", 8),
    QLatin1String("pdf_edit", 8),
    QLatin1String("pdf_text_edit", 13),
    QLatin1String("pdf_pic_edit", 12),
    QLatin1String("pdf_img_extract", 15),
    QLatin1String("pdf_compress", 12),
    QLatin1String("pdf_cover_pen", 13),
    QLatin1String("pdf_num_edit", 12),
    QLatin1String("pdf_page_edit", 13),
    QLatin1String("pdf_page_move", 13),
    QLatin1String("pdf_pagehf_edit", 15),
    QLatin1String("pdf_watermark_edit", 18),
    QLatin1String("pdf_batch_output", 16),
    QLatin1String("pdf_sign", 8),
    QLatin1String("pdf_page_extract", 16),
    QLatin1String("pdf_page_output", 15),
    QLatin1String("pdf_ocr", 7),
    QLatin1String("pdf_background", 14),
    QLatin1String("pdf_link", 8),
    QLatin1String("pdf_annex", 9),
    QLatin1String("pdf_page_copy", 13),
    QLatin1String("pdf_page_split", 14),
    QLatin1String("pdf_page_crop", 13),
    QLatin1String("pdf_table_extract", 17),
    QLatin1String("pdf_scan_edit", 13),
    QLatin1String("pdf_scan_optimize", 17),
    QLatin1String("pdf_batch_adddelwm", 18),
    QLatin1String("pdf_edit_path", 13),
    QLatin1String("pdf_videoedit", 13),
    QLatin1String("pdf_audioedit", 13),
    QLatin1String("pdf_videosave", 13),
    QLatin1String("pdf_audiosave", 13),
    QLatin1String("pdf_page_replace", 16),
    QLatin1String("pdf_page_size", 13),
    QLatin1String("pdf_password", 12),
    QLatin1String("pdf_2html", 9),
    QLatin1String("pdf_page_manage", 15),
    QLatin1String("pdf_2doc_bypage_local", 21),
    QLatin1String("pdf_2et_bypage_local", 20),
    QLatin1String("pdf_2ppt_bypage_local", 21),
    QLatin1String("pdf_annotate", 12),
    QLatin1String("pdf_annotation", 14),
    QLatin1String("pdf_output_annotate", 19),
    QLatin1String("pdf_watermark", 13),
    QLatin1String("pdf_txt_extract", 15),
    QLatin1String("pure_image_pdf", 14),
    QLatin1String("output_highlight", 16),
    QLatin1String("pdf_watermark_output", 20),
    QLatin1String("pdf_new", 7),
    QLatin1String("pdf_encryption", 14),
    QLatin1String("pdf_virtualprint", 16),
    QLatin1String("table_extract", 13),
    QLatin1String("pdf_invoiceprint", 16),
    QLatin1String("pdf_formedit", 12),
    QLatin1String("pdf_gencatalogue", 16),
    QLatin1String("pdf_genbookmark", 15),
    QLatin1String("pdf_delete_blankpage", 20),
    QLatin1String("pdf_identifyform", 16),
    QLatin1String("pdf_reverseorder", 16),
    QLatin1String("img_output", 10),
    QLatin1String("screenshot", 10),
    QLatin1String("advanced_print", 14),
    //QLatin1String("doc_check", 9),
    QLatin1String("mul_print", 9),
    QLatin1String("pdf_2doc_bypage", 15),
    QLatin1String("pdf_2et", 7),
    QLatin1String("pdf_2et_bypage", 14),
    QLatin1String("pdf_2ppt", 8),
    QLatin1String("pdf_2ppt_bypage", 15),
    QLatin1String("delete_blankpage", 16),
    QLatin1String("file_backup", 11),
    QLatin1String("background", 10)
};

void GetSNPrivileges(QList<QString>& outList) {
    Logger::instance().writer().stream() << "[AuthBypass] GetSNPrivileges() called";

    for (const QString& feature : _allFeatures) {
        outList.append(feature);
    }
}

IKIntranetAuthorize& _kintranetauthsdk_GetAuthObject() {
    Logger::instance().writer().stream() << "[AuthBypass] GetAuthObject() called";

    static KIntranetAuthorize instance;
    return instance;
}
